name: Auto SignIn (manual)
on:
  workflow_dispatch: # 有这个就能在页面点"Run workflow"立刻运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 用 Secret 写入 configure/cookie.json（不要把 cookie 写进仓库）
      - name: Write configs (data.json & cookie.json) from secret
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
        run: |
          mkdir -p configure
          python3 << 'EOF'
          import os
          import json
          import pathlib
          
          # 获取环境变量
          cookie_value = os.environ.get('MY_COOKIE', '').strip()
          print(f"Cookie value length: {len(cookie_value)}")
          
          # 创建配置
          cfg = {
              "users": [
                  {
                      "username": "",
                      "password": "",
                      "cookie": cookie_value,
                      "cookies": cookie_value,
                      "login": "cookie"
                  }
              ]
          }
          
          # 确保目录存在
          config_dir = pathlib.Path('configure')
          config_dir.mkdir(exist_ok=True)
          
          # 写入配置文件
          data_file = config_dir / 'data.json'
          cookie_file = config_dir / 'cookie.json'
          
          with open(data_file, 'w', encoding='utf-8') as f:
              json.dump(cfg, f, ensure_ascii=False, indent=2)
          
          with open(cookie_file, 'w', encoding='utf-8') as f:
              json.dump({"cookie": cookie_value}, f, ensure_ascii=False, indent=2)
          
          print("Config files written successfully")
          print(f"data.json content: {json.dumps(cfg, indent=2)}")
          EOF
          
      - name: Debug config files
        run: |
          echo "=== Checking config files ==="
          ls -la configure/
          echo "=== data.json content ==="
          cat configure/data.json
          echo "=== cookie.json content ==="
          cat configure/cookie.json
          
      - name: Run service
        working-directory: ./src
        run: python service.py
