name: Auto SignIn (manual)
on:
  workflow_dispatch: # 有这个就能在页面点"Run workflow"立刻运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 使用 Mini 版本，直接修改代码中的 cookie
      - name: Update mini.py with cookie
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # 备份原文件
          cp src/mini.py src/mini.py.bak
          
          # 获取环境变量
          COOKIE_VALUE="${MY_COOKIE:-}"
          API_KEY_VALUE="${API_KEY:-}"
          
          echo "Cookie length: ${#COOKIE_VALUE}"
          echo "API Key length: ${#API_KEY_VALUE}"
          
          if [ -z "$COOKIE_VALUE" ]; then
            echo "ERROR: MY_COOKIE is empty!"
            exit 1
          fi
          
          # 使用 Python 来安全地替换，避免特殊字符问题
          python3 << 'EOF'
          import os
          import re
          
          # 读取环境变量
          cookie_value = os.environ.get('MY_COOKIE', '')
          api_key_value = os.environ.get('API_KEY', '')
          
          # 读取 mini.py 文件
          with open('src/mini.py', 'r', encoding='utf-8') as f:
              content = f.read()
          
          # 替换 cookie 和 api key
          content = re.sub(r'cookie = """XXXXXXX"""', f'cookie = """{cookie_value}"""', content)
          content = re.sub(r'TwoCaptcha_apikey = "xxxxxxxxxx"', f'TwoCaptcha_apikey = "{api_key_value}"', content)
          
          # 写回文件
          with open('src/mini.py', 'w', encoding='utf-8') as f:
              f.write(content)
          
          print("mini.py updated successfully")
          EOF
          
      - name: Debug mini.py content
        run: |
          echo "=== Checking if mini.py exists ==="
          ls -la src/
          echo "=== First few lines of mini.py ==="
          head -10 src/mini.py
          echo "=== Checking cookie replacement ==="
          grep -n "cookie.*XXXXXXX\|TwoCaptcha_apikey" src/mini.py || echo "Cookie/API key lines not found"
          
      - name: Run mini version
        working-directory: ./src
        run: python mini.py
