name: Auto SignIn (manual)
on:
  workflow_dispatch: # 有这个就能在页面点"Run workflow"立刻运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 创建兼容的配置文件（同时支持 cookie 和 data.json）
      - name: Write compatible config from cookie
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
        run: |
          mkdir -p configure
          python3 << 'EOF'
          import os
          import json
          import pathlib
          
          # 获取环境变量
          cookie_value = os.environ.get('MY_COOKIE', '').strip()
          
          print(f"Cookie value length: {len(cookie_value)}")
          
          if not cookie_value:
              print("ERROR: MY_COOKIE is empty!")
              exit(1)
          
          # 确保目录存在
          config_dir = pathlib.Path('configure')
          config_dir.mkdir(exist_ok=True)
          
          # 创建 cookie.json（新方式）
          cookie_config = {
              "cookie": cookie_value,
              "api_key": ""  # 先留空，如果需要验证码服务再填写
          }
          
          cookie_file = config_dir / 'cookie.json'
          with open(cookie_file, 'w', encoding='utf-8') as f:
              json.dump(cookie_config, f, ensure_ascii=False, indent=2)
          
          # 创建 data.json（老方式，避免程序报错）
          data_config = {
              "users": [
                  {
                      "username": "",
                      "password": "", 
                      "cookie": cookie_value,
                      "cookies": cookie_value,
                      "login": "cookie",
                      "api_key": ""
                  }
              ]
          }
          
          data_file = config_dir / 'data.json'
          with open(data_file, 'w', encoding='utf-8') as f:
              json.dump(data_config, f, ensure_ascii=False, indent=2)
          
          print("Config files written successfully")
          print(f"cookie.json content: {json.dumps(cookie_config, indent=2)}")
          print(f"data.json content: {json.dumps(data_config, indent=2)}")
          EOF
          
      - name: Debug config files
        run: |
          echo "=== Checking config files ==="
          ls -la configure/
          echo "=== cookie.json content ==="
          cat configure/cookie.json
          echo "=== data.json content ==="
          cat configure/data.json
          
      - name: Run service
        working-directory: ./src
        run: python service.py
