name: Auto SignIn (manual)

on:
  workflow_dispatch:  # 有这个，页面上才会出现 “Run workflow” 按钮

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write cookie.json from secret
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}  # 先在 Settings → Secrets 新建这个
        run: |
          mkdir -p configure
          python - <<'PY'
import os, json, pathlib
cookie = os.environ.get("MY_COOKIE","").strip()
pathlib.Path("configure").mkdir(exist_ok=True)
with open("configure/cookie.json","w",encoding="utf-8") as f:
    json.dump({"cookie": cookie}, f, ensure_ascii=False)
print("cookie.json written")
PY

      - name: Run service
        working-directory: ./src
        run: python service.py
