name: Auto SignIn (manual)
on:
  workflow_dispatch: # 有这个就能在页面点"Run workflow"立刻运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 尝试只用 Cookie 的配置
      - name: Write cookie-only config from secret
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
        run: |
          mkdir -p configure
          python3 << 'EOF'
          import os
          import json
          import pathlib
          
          # 获取环境变量
          cookie_value = os.environ.get('MY_COOKIE', '').strip()
          
          print(f"Cookie value length: {len(cookie_value)}")
          
          if not cookie_value:
              print("ERROR: MY_COOKIE is empty!")
              exit(1)
          
          # 创建只有 cookie 的配置
          cookie_config = {
              "cookie": cookie_value
          }
          
          # 确保目录存在
          config_dir = pathlib.Path('configure')
          config_dir.mkdir(exist_ok=True)
          
          # 写入 cookie.json 配置文件
          cookie_file = config_dir / 'cookie.json'
          with open(cookie_file, 'w', encoding='utf-8') as f:
              json.dump(cookie_config, f, ensure_ascii=False, indent=2)
          
          print("Cookie-only config file written successfully")
          print(f"cookie.json content: {json.dumps(cookie_config, indent=2)}")
          EOF
          
      - name: Debug config files
        run: |
          echo "=== Checking config files ==="
          ls -la configure/
          echo "=== cookie.json content ==="
          cat configure/cookie.json
          
      - name: Run service (cookie-only attempt)
        working-directory: ./src
        run: python service.py
