name: Auto SignIn (manual)

on:
  workflow_dispatch:   # 手动触发（页面能点 Run workflow）
  # schedule:          # 想每天定时跑再打开这段
  #   - cron: '15 8 * * *'   # UTC 08:15，每天一次

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write configs (data.json & cookie.json) from secret
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
        run: |
          mkdir -p configure
          python - <<'PY'
import os, json, pathlib
c = os.environ.get("MY_COOKIE", "").strip()
cfg = {
  "users": [
    {
      "username": "",
      "password": "",
      "cookie": c,
      "cookies": c,
      "login": "cookie"
    }
  ]
}
p = pathlib.Path("configure")
(p / "data.json").write_text(json.dumps(cfg, ensure_ascii=False), encoding="utf-8")
(p / "cookie.json").write_text(json.dumps({"cookie": c}, ensure_ascii=False), encoding="utf-8")
print("config files written")
PY

      - name: Run service
        working-directory: ./src
        run: python service.py
