name: Auto SignIn (manual)

on:
  workflow_dispatch:  # 有这个就能在页面点“Run workflow”立刻运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 用 Secret 写入 configure/cookie.json（不要把 cookie 写进仓库）
      - name: Write cookie.json from secret
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
        run: |
          mkdir -p configure
          python -c 'import os,json,sys; open("configure/cookie.json","w",encoding="utf-8").write(json.dumps({"cookie": os.environ.get("MY_COOKIE","").strip()}, ensure_ascii=False))'
          echo "cookie.json written"

      - name: Run service
        working-directory: ./src
        run: python service.py
